resources:
  - name: spring-boot-service
    type: git
    source:
      uri: https://github.com/ChuckPhilips/maven.git
      branch: main

  - name: spring-boot-service-docker-repository
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: ((docker-hub-username))/((docker-hub-repo-name))

caches:
  - path: $HOME/.m2/repository

jobs:
  - name: test
    public: true

    plan:
      - get: spring-boot-service
        trigger: true
      - task: mvn-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3.6.0-jdk-8-alpine
          inputs:
            - name: spring-boot-service
          run:
            path: 'mvn'
            args:
              - -f
              - spring-boot-service/pom.xml
              - clean
              - test

  - name: package
    public: true
    serial: true
    plan:
      - get: spring-boot-service
        trigger: true
        passed: [test]
      - task: mvn-package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: maven
              tag: 3.6.0-jdk-8-alpine
          inputs:
            - name: spring-boot-service
          run:
            path: 'mvn'
            args:
              - -f
              - spring-boot-service/pom.xml
              - clean
              - package

          outputs:
            - name: spring-boot-service-out
              path: spring-boot-service

      - put: spring-boot-service-docker-repository
        params:
          build: spring-boot-service-out
